### ISSUE TITLE
Is there reason a for this?

### ISSUE THREAD

**Issue by joedf** [AfterLemon/Class_Console#5]
On the following line: https://github.com/AfterLemon/Class_Console/blob/master/Class_Console.ahk#L347

I would think that this
`return (x?x:0)` is the same as `return x`

Is there any particular reason?

**Comment by AfterLemon** [comment]
If x is blank, it will return 0, just as one would expect from a function.

**Comment by joedf** [comment]
ahh i ok, i thought that it may have been that, ok thanks! :)
