### ISSUE TITLE
Console not shown when used in a function

### ISSUE THREAD

**Issue by paulhybryant** [AfterLemon/Class_Console#6]
Here is a sample code:

^#-::
test()
return

test() {
    MsgBox, "Yay"
    Class_Console("VariableList",100,100,400,600,"Variable List")
        VariableList.log("Variable List:This is working")
        VariableList.show()
        MsgBox, "Great!"
}

The two MsgBox are shown, but the console window is never shown.

However,
^#-::
        Class_Console("VariableList",100,100,400,600,"Variable List")
        VariableList.log("Variable List:This is working")
        VariableList.show()
return

works. Is this intended?

**Comment by paulhybryant** [comment]
Sorry this is due to my limited understanding of autohotkey. Closing this issue.

**Comment by AfterLemon** [comment]
If you need any assistance with this, let me know. I'll try to respond
within the day.

**Comment by paulhybryant** [comment]
Thanks for the reply.

Right now I used a hotkey to create the console object, and use global in function to access it and that works.

Something like this.

^#D::
Class_Console("foo", ...)

test() {
global foo
foo.log("bar")
}

But I am curious why the window won't show in the following case;

^#-::
test()
return

test() {
MsgBox, "Yay"
Class_Console("VariableList",100,100,400,600,"Variable List")
VariableList.log("Variable List:This is working")
VariableList.show()
MsgBox, "Great!"
}

Thanks!

**Comment by AfterLemon** [comment]
Ahh, pretty much the same reason you have to use global on the variable
when you create the console outside the function. The Class_Console
function makes the variable containing the Console global from within a
function (or class), which makes it apply to the script as a whole. You
need to ALSO declare the variable you intend to use for the console as
global inside any functions that call a new one.

^#-::
test()
return

test() {

global VariableList

MsgBox, "Yay"
Class_Console("VariableList",100,100,400,600,"Variable List")
VariableList.log("Variable List:This is working")
VariableList.show()
MsgBox, "Great!"
}

**Comment by paulhybryant** [comment]
oh I see. Thanks!
